version: "3"

services:

  prod:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        CI_BUILD_ID: ${CI_BUILD_ID}
        CI_BUILD_REF: ${CI_BUILD_REF}
        CI_BUILD_TIME: ${CI_BUILD_TIME}
        CI_REGISTRY_IMAGE: ${CI_REGISTRY_IMAGE}
    image: ${DOCKER_IMAGE_PROD:-teracy/blog:latest}
    environment:
      - VIRTUAL_HOST=blog.teracy.dev
      - HTTPS_METHOD=noredirect
    ports:
      - 80
    # to get this work with https://github.com/jwilder/nginx-proxy
    # related: https://github.com/jwilder/nginx-proxy/issues/305
    network_mode: bridge
